### ISSUE TITLE
Having "Allow cookies from sites" unticked breaks the pop-up panel

### ISSUE THREAD

**Issue by mertzi** [mozilla/testpilot-containers#395]
Hello! I have a strict white list policy for cookies and only allow them for sites where I need them (most of them are session only). This seems to break the panel and I guess that's because the Containers add-on needs to be able to store it's own cookies. However if I allow cookies and get Containers working properly and open a container etc and then go to settings and click the "Show Cookies..."-button nothing is listed. How can I white list an add-on?

**Comment by mertzi** [comment]
Worth to mention is that the pop-up works with the built in Containers i.e. "privacy.userContext.enabled" set to true in about:config, even with cookies disabled.

**Comment by groovecoder** [comment]
The Containers add-on uses localStorage, which I believe is controlled by the same prefs/allow-lists as cookies.

But it sounds like this might be a dupe or regression of https://github.com/mozilla/testpilot-containers/issues/302, which should be fixed in the latest (2.0.0) release? 😢

**Comment by JohnLGalt** [comment]
I hope not - I'm still on my test profile with Containers, but was planning on moving it over to the default profile I use for just about everything.  if it has issues with CM (and, specifically, the way that CM controls cookies by globally denying them and then allowing the  user to accept them on a site / domain basis) then I am going ot have to wait - I use CM religiously. And NoScript, RequestPolicy Continued, and uBlock Origin.

I think only CM is going to get in the way, but still - if they are mutually exclusive because of hte way the cookies are handled in containers, then that is going to be a deal breaker for one or the other.

I've been in contact with Tony Schilling, dev of CM, and he says there is a 50% chance that he can make it compatible with both electrolysis as well as the Webextensions api, so we'll see - if he does, I'm going to continue using it.

**Comment by mertzi** [comment]
Unfortunately 2.0.0 didn't solve the issue. The possible dupe mentions several add-ons, but the Firefox installation I've been testing containers with has no extensions besides Containers and Test pilot, and if I allow cookies the drop down works.
I don't know if this is relevant but I use FF portable from portableapps.com and it's only on v.52.0.1

**Comment by LynnMaISD** [comment]
I am still seeing this error with cookies disabled on FF developer build 54.0a2 with no addons but containers showing up. I'm in a similar spot as @JohnLGalt with regard to a strict whitelist policy for my cookies, but I am willing to test the addon on one of the machines I have FF dev installed on. I am unfamiliar with firefox addon debugging, however I am familiar with troubleshooting in general and I know JS. Containers is the entire reason I joined the test pilot program, so I would really love to see this work. 

Will start by following the suggestions in #302 and debugging the addon. If anyone has any suggestions, by all means please let me know.

**Comment by the8472** [comment]
> The Containers add-on uses localStorage

webextensions have their own storage API which is not disabled by cookies settings, couldn't it use that?

**Comment by jonathanKingston** [comment]
@the8472 yeah it should, everything else does. We should fix that at least as it causes other issues.

**Comment by dannycolin** [comment]
@mertzi Can you still reproduce in the latest version?
